[package]
name = "spawn-at"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
zbus = { version = "4.4", features = ["blocking", "tokio"] }
tokio = { version = "1.38", features = ["rt-multi-thread", "macros", "process", "time"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dialoguer = { version = "0.11", default-features = false, features = ["editor"] }
toml = "1.1.6"
futures-util = "0.3.34"
async-trait = "0.1.92"
strsim = "0.11"
